Repository php-webdriver/php-webdriver, pull requests merged in 2019-11, with the labels that each got.

#670 Compatibility with Symfony 5
  CHANGELOG.md
  composer.json
Labels: CLA Signed

#560 W3C-compliant implementation, native geckodriver support
  .travis.yml
  CONTRIBUTING.md
  lib/AbstractWebDriverCheckboxOrRadio.php
  lib/Cookie.php
  lib/Exception/WebDriverException.php
  lib/Interactions/WebDriverActions.php
  lib/Remote/DriverCommand.php
  lib/Remote/HttpCommandExecutor.php
  lib/Remote/JsonWireCompat.php
  lib/Remote/RemoteMouse.php
  lib/Remote/RemoteTargetLocator.php
  lib/Remote/RemoteWebDriver.php
  lib/Remote/RemoteWebElement.php
  lib/WebDriverDimension.php
  lib/WebDriverOptions.php
  lib/WebDriverPoint.php
  lib/WebDriverTimeouts.php
  tests/functional/RemoteWebDriverCreateTest.php
  tests/functional/RemoteWebDriverFindElementTest.php
  tests/functional/RemoteWebDriverTest.php
  tests/functional/RemoteWebElementTest.php
  tests/functional/WebDriverActionsTest.php
  tests/functional/WebDriverTestCase.php
  tests/functional/web/escape_css.html
  tests/functional/web/upload.html
Labels: CLA Signed

#546 Allow combined not() and presenceOfElementLocated() functionality
  CHANGELOG.md
  lib/WebDriverExpectedCondition.php
  tests/unit/WebDriverExpectedConditionTest.php
Labels: CLA Signed

#602 Use polyfill-mbstring when ext-mbstring isn't available
  composer.json
Labels: CLA Signed

#673 Make chromeOptions compatible with both JsonWire and W3C protocols
  .travis.yml
  lib/Chrome/ChromeOptions.php
  lib/Remote/RemoteWebDriver.php
Labels: CLA Signed, w3c-protocol

#674 Enable W3C protocol for Chrome 🎉
  .travis.yml
  lib/Remote/RemoteWebDriver.php
  tests/functional/RemoteWebDriverFindElementTest.php
  tests/functional/RemoteWebDriverTest.php
  tests/functional/RemoteWebElementTest.php
  tests/functional/WebDriverActionsTest.php
  tests/functional/WebDriverTestCase.php
Labels: CLA Signed, w3c-protocol

#678 Convert Capabilities to W3C compatible
  lib/Remote/DesiredCapabilities.php
  lib/Remote/RemoteWebDriver.php
  tests/unit/Remote/DesiredCapabilitiesTest.php
Labels: CLA Signed

#680 Run geckodriver tests in headless mode
  tests/functional/WebDriverTestCase.php
Labels: CLA Signed

#679 Add W3C window size and position commands
  lib/Remote/HttpCommandExecutor.php
  tests/functional/WebDriverWindowTest.php
Labels: CLA Signed, w3c-protocol

#685 Use W3C protocol on part of Sauce Labs builds
  .travis.yml
  lib/Remote/RemoteWebElement.php
  tests/functional/FileUploadTest.php
  tests/functional/WebDriverAlertTest.php
  tests/functional/WebDriverCheckboxesTest.php
  tests/functional/WebDriverRadiosTest.php
  tests/functional/WebDriverTestCase.php
  tests/functional/WebDriverTimeoutsTest.php
Labels: CLA Signed, w3c-protocol

#687 Correct mouseUp W3C Action
  lib/Remote/RemoteMouse.php
  tests/functional/WebDriverActionsTest.php
Labels: CLA Signed

#682 Make ActiveElement endpoint W3C compatible
  lib/Remote/HttpCommandExecutor.php
  tests/functional/RemoteTargetLocatorTest.php
Labels: CLA Signed, w3c-protocol

#690 Minor codestyle improvements and unifications
  .php_cs.dist
  phpstan.neon
  tests/functional/RemoteWebDriverCreateTest.php
  tests/functional/RemoteWebDriverTest.php
  tests/functional/WebDriverActionsTest.php
  tests/functional/WebDriverAlertTest.php
  tests/functional/WebDriverByTest.php
  tests/functional/WebDriverCheckboxesTest.php
  tests/functional/WebDriverNavigationTest.php
  tests/functional/WebDriverRadiosTest.php
  tests/functional/WebDriverSelectTest.php
  tests/functional/WebDriverTimeoutsTest.php
  tests/unit/CookieTest.php
  tests/unit/Exception/WebDriverExceptionTest.php
  tests/unit/Interactions/Internal/WebDriverButtonReleaseActionTest.php
  tests/unit/Interactions/Internal/WebDriverClickActionTest.php
  tests/unit/Interactions/Internal/WebDriverClickAndHoldActionTest.php
  tests/unit/Interactions/Internal/WebDriverContextClickActionTest.php
  tests/unit/Interactions/Internal/WebDriverCoordinatesTest.php
  tests/unit/Interactions/Internal/WebDriverDoubleClickActionTest.php
  tests/unit/Interactions/Internal/WebDriverKeyDownActionTest.php
  tests/unit/Interactions/Internal/WebDriverKeyUpActionTest.php
  tests/unit/Interactions/Internal/WebDriverMouseMoveActionTest.php
  tests/unit/Interactions/Internal/WebDriverMouseToOffsetActionTest.php
  tests/unit/Interactions/Internal/WebDriverSendKeysActionTest.php
  tests/unit/Remote/DesiredCapabilitiesTest.php
  tests/unit/Remote/HttpCommandExecutorTest.php
  tests/unit/Remote/RemoteWebDriverTest.php
  tests/unit/Support/XPathEscaperTest.php
  tests/unit/WebDriverOptionsTest.php
Labels: CLA Signed, code quality

#694 Allow specification of alternate host for fixtures
  tests/functional/WebDriverTestCase.php
Labels: CLA Signed
