Repository php-webdriver/php-webdriver, pull requests merged in 2019-12, with the labels that each got.

#693 Allow specification of firefox options for non-gecko
  tests/functional/WebDriverTestCase.php
Labels: CLA Signed

#700 Improve code coverage
  lib/Remote/RemoteTargetLocator.php
  tests/functional/RemoteTargetLocatorTest.php
  tests/functional/RemoteWebDriverTest.php
Labels: CLA Signed, code quality

#695 Accept W3C capabilitites from the browser and provide them as OSS ones
  lib/Remote/DesiredCapabilities.php
  lib/Remote/RemoteWebDriver.php
  tests/functional/RemoteWebDriverCreateTest.php
Labels: CLA Signed, w3c-protocol

#696 Change environment variable defining path to ChromeDriver executable
  CHANGELOG.md
  lib/Chrome/ChromeDriverService.php
  tests/functional/Chrome/ChromeDriverServiceTest.php
  tests/functional/Chrome/ChromeDriverTest.php
Labels: CLA Signed

#707 Use clear endpoint to clear element content even in W3C mode
  lib/Remote/RemoteWebElement.php
Labels: CLA Signed, w3c-protocol

#697 Maintain BC for renamed TimeOutException
  composer.json
Labels: CLA Signed

#701 Add take element screenshot command
  CHANGELOG.md
  lib/Remote/DriverCommand.php
  lib/Remote/HttpCommandExecutor.php
  lib/Remote/RemoteWebElement.php
  lib/WebDriverElement.php
  tests/functional/RemoteWebElementTest.php
Labels: CLA Signed

#716 Add PHP 7.4 build (attempt #2)
  .travis-php74.ini
  .travis.yml
Labels: CLA Signed

#717 Use W3C command to get named cookie
  CHANGELOG.md
  lib/Remote/DriverCommand.php
  lib/Remote/HttpCommandExecutor.php
  lib/WebDriverOptions.php
  tests/functional/WebDriverOptionsCookiesTest.php
Labels: CLA Signed, w3c-protocol

#718 Add switch to parent frame command
  lib/Remote/HttpCommandExecutor.php
  lib/Remote/RemoteTargetLocator.php
  lib/WebDriverTargetLocator.php
  tests/functional/RemoteTargetLocatorTest.php
Labels: CLA Signed, w3c-protocol

#725 Rerun failed tests to improve build stability
  tests/functional/WebDriverTestCase.php
Labels: CLA Signed, code quality
