Repository php-webdriver/php-webdriver, pull requests merged in 2022-08, with the labels that each got.

#995 Replace no-response probot with 'lee-dohm/no-response' action
  .github/no-response.yml
  .github/workflows/no-response.yaml
Labels: waiting for reaction

#994 Mark getAllSessions() deprecated in W3C WebDriver
  lib/Remote/RemoteWebDriver.php
Labels: w3c-protocol

#997 Run functional tests on Selenium server 4.3
  .github/workflows/tests.yaml
Labels: code quality

#968 Add tests to make sure Firefox profile is working
  tests/functional/Firefox/FirefoxProfileTest.php
  tests/functional/web/index.html
Labels: code quality
